### ISSUE TITLE
Инициализация проекта (back)

### ISSUE THREAD

**Issue by jjagorka** [YagaTalk/YagaTalkMVP#1]
**Что нужно**
Репу + каркас для приложения, который можно наполнять бизнес-логикой:
1. должно запускаться через идею: main() -> run
2. должно собираться в executable Jar. Пример скрипта `./gradlew bootJar`. Проверить, что запускается `java -jar {имя файла}`
3. порт по умолчанию 8082
4. при старте должно подключаться к базе и инициализировать ее с помощью flyway-скриптов. Для проверки можно создавать какую-нибудь временную таблицу, в последдствии удалим
5. должен быть REST-ресурс `GET /health`, который вернет 204 (No content) 

**Что делать**
1. Создать репу в рамках организации
2. Сконвертировать этот Draft (?) в issue и прикрепить к репе.
3. В репе:
В директории `./backend` засетапить Spring Boot (последней версии) проект.
Использовать Gradle последней стабильной версии + Gradle Wrapper
Зависимости, которые пригодятся:
- spring-boot-starter-web
- spring-boot-starter-jdbc (Обсудить, может JPA или Data JDBC)
- подключить драйвер Postgres
- spring-boot-starter-webflux (оттуда возьмем WebClient). Есть аналог постарее RestTemplate, но лучше сразу использовать non-blocking клиент, потому что ответов от OpenAI API придется ждать долго и много
- [flyway](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.migration-tool.flyway)

Со звездочкой:
1. Установить на комп Docker. В проекте в `./devenv` положить файл `docker-compose.yml` (содержимое ниже). Это чтобы новый разработчик типа меня мог быстро базу поднять не скачивая никакой постгрес. Приложение по умолчанию должно быть настроено на базу, которая в контейнере.
```yaml
version: '3.5'
services:

  dbpostgres:
    image: postgres:13-alpine
    networks:
      - yaga-talk
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: yaga-talk

networks:
  yaga-talk:
    name: yaga-talk

```
2. в `./requests` положить файл `health.http` (содердимое ниже) из вложений. Это файл для https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html чтобы можно было быстро руками проверить что метод работает
```

GET http://localhost:8082/health

```
